### ISSUE TITLE
请问 引用类型(外键) 支持多选吗

### ISSUE THREAD

**Issue by hgaong** [msgbyte/tushan#16]
现在支持的是在学生那里选择班级 ，但有些场景是相反的，比如 在班级那里选择多个学生，这种支持吗 ，不支持的话应该如何自定义

**Comment by moonrailgun** [comment]
外键永远是单选的。在数据库层面你没有办法选择数组。
你说的可能是反向外键，即创建学生记录，然后把学生的班级id指向班级的id

如果你是mongodb这样的nosql。你可以参考文档 https://tushan.msgbyte.com/guide/custom-field 实现一个array类型。

重点是你需要实现相关的后端代码以更新两张表的关联关系

**Comment by hgaong** [comment]
> 外键永远是单选的。在数据库层面你没有办法选择数组。 你说的可能是反向外键，即创建学生记录，然后把学生的班级id指向班级的id
> 
> 如果你是mongodb这样的nosql。你可以参考文档 https://tushan.msgbyte.com/guide/custom-field 实现一个array类型。
> 
> 重点是你需要实现相关的后端代码以更新两张表的关联关系

谢谢 实现了 ，真强大
