### ISSUE TITLE
createBooleanField编辑时有多余内容

### ISSUE THREAD

**Issue by Haiananan** [msgbyte/tushan#2]
<img width="1440" alt="image" src="https://github.com/msgbyte/tushan/assets/87032113/9d24fde9-6f40-4aa4-a77e-fe957cf69c2d">

export const SystemFields = [
  createTextField('openAIKeys', { label: 'openAIKeys，逗号隔开' }),
  createTextField('openAITrainingKeys', { label: 'openAITrainingKeys' }),
  createTextField('gpt4Key', { label: 'gpt4Key' }),
  createTextField('vectorMaxProcess', { label: '向量最大进程' }),
  createTextField('qaMaxProcess', { label: 'qa最大进程' }),
  createTextField('pgIvfflatProbe', { label: 'pg 探针数量' }),
  createBooleanField('sensitiveCheck', { label: '敏感词校验' })
];

如图所示，使用createBooleanField时，toggle底下还会有个类似Label的东西

**Comment by moonrailgun** [comment]
fixed in v0.2.31

**Comment by Haiananan** [comment]
ok
