### ISSUE TITLE
希望可以在路径里直接指定筛选的内容

### ISSUE THREAD

**Issue by cationCatM** [msgbyte/tushan#6]
比如点用户表的某个用户，直接跳转到post表，并且筛选只显示当前用户的内容。

另外希望可以指定默认的排序字段。目前是id，有时候id是uuid生成的，希望是按创建时间来排序。要么默认请求别带_sort

**Comment by moonrailgun** [comment]
tushan v0.2.38 在ListTable 增加了`defaultSort` 用于替换默认排序方式。你可以手动修改为按自定义字段排序

并增加了url query string 在 ListTable 的过滤条件的映射，你可以通过手动构建查询语句跳转来实现你的需求

**Comment by cationCatM** [comment]
模板可以更新下了，现在模板还是0.2.36

**Comment by moonrailgun** [comment]
> 模板可以更新下了，现在模板还是0.2.36

DONE
